In [1]:
import numpy as np

## get_random simple function:

In [2]:
def get_random(n_samples=10, distribution='normal', mu=0, sigma=0.1, interval=5, trials=10, prob=.5):
    if distribution == 'normal':
        print(f'Paramters: ')
        print(f'samples: {n_samples}, distribution: {distribution}, mu: {mu}, sigma: {sigma}')
        return np.random.normal(mu, sigma, n_samples)
    elif distribution == 'poisson':
        print(f'Paramters: ')
        print(f'samples: {n_samples}, distribution: {distribution}, interval: {interval}')
        return np.random.poisson(interval, n_samples)
    elif distribution == 'binomial':
        print(f'Paramters: ')
        print(f'samples: {n_samples}, distribution: {distribution}, trials: {trials}, prob: {prob}')
        return np.random.binomial(trials, prob, n_samples)
    else:
        print(f'Paramters: ')
        print(f'samples: {n_samples}, distribution: {distribution}')
        return "Distribution not supported!"

In [3]:
get_random(n_samples=5, distribution='normal', mu=0, sigma=0.4)

Paramters: 
samples: 5, distribution: normal, mu: 0, sigma: 0.4


array([-0.60367105, -0.59711091,  0.32772432,  0.02498374, -0.06856117])

In [4]:
get_random(n_samples=5, distribution='poisson', interval=10)

Paramters: 
samples: 5, distribution: poisson, interval: 10


array([5, 9, 9, 5, 9])

In [5]:
get_random(n_samples=5, distribution='binomial', trials=5, prob=.6)

Paramters: 
samples: 5, distribution: binomial, trials: 5, prob: 0.6


array([3, 3, 3, 3, 4])

In [6]:
get_random(n_samples=5, distribution='multinomial')

Paramters: 
samples: 5, distribution: multinomial


'Distribution not supported!'

## GetRandomNums class:

In [7]:
class GetRandomNums(object):
    def __init__(self, n_samples, distribution, mu=0, sigma=0.1, interval=5, trials=10, prob=.5, draw=[]):
        self.n_samples = n_samples
        self.distribution = distribution
        self.mu = mu
        self.sigma = sigma
        self.interval = interval
        self.trials = trials
        self.prob = prob
        self._draw = draw
        
    def normal_dist(self, mu, sigma):
        return np.random.normal(mu, sigma, self.n_samples)
    
    def poisson_dist(self, interval):
        return np.random.poisson(interval, self.n_samples)
    
    def binomial_dist(self, trials, prob):
        return np.random.binomial(trials, prob, self.n_samples)
    
    def draw(self):
        if self.distribution == 'normal':
            print(f'''Parameters of the draw: \n
                samples size: {self.n_samples} \n
                distribution: {self.distribution} \n
                mu: {self.mu} \n
                sigma: {self.sigma}
            ''')
            
            self._draw = self.normal_dist(self.mu, self.sigma)
            return self._draw
        elif self.distribution == 'poisson':
            print(f'''Parameters of the draw: \n
                samples size: {self.n_samples} \n
                distribution: {self.distribution} \n
                interval: {self.interval} \n
            ''')
            
            self._draw = self.poisson_dist(self.interval)
            return self._draw
        elif self.distribution == 'binomial':
            print(f'''Parameters of the draw: \n
                samples size: {self.n_samples} \n
                distribution: {self.distribution} \n
                trials: {self.trials} \n
                prob: {self.prob}
            ''')
            self._draw = self.binomial_dist(self.trials, self.prob)
            return self._draw
        else:
            print(f'''Parameters of the draw: \n
                samples size: {self.n_samples} \n
                distribution: {self.distribution} \n
            ''')
            
            return "Distribution not supported!"
        
    def summarize(self):
        if len(self._draw) == 0:
            return 'Please draw a random sample first!'
        random_sample = self._draw
        rnd_sample_min = np.min(random_sample)
        rnd_sample_max = np.max(random_sample)
        rnd_sample_mean = np.mean(random_sample)
        rnd_sample_std = np.std(random_sample)
        
        return f'min: {rnd_sample_min}, max: {rnd_sample_max}, mean: {rnd_sample_mean}, std: {rnd_sample_std}'

In [8]:
summ = GetRandomNums(n_samples = 5, distribution = 'normal')
summ.summarize()

'Please draw a random sample first!'

In [9]:
rand1 = GetRandomNums(n_samples = 5, distribution = 'normal')
print(rand1.draw())
rand1.summarize()

Parameters of the draw: 

                samples size: 5 

                distribution: normal 

                mu: 0 

                sigma: 0.1
            
[ 0.04172006  0.0923807   0.02645455 -0.00710711 -0.00346559]


'min: -0.00710710701999073, max: 0.09238069884665677, mean: 0.029996522979300562, std: 0.03616120772612344'

In [10]:
rand2 = GetRandomNums(n_samples = 5, distribution = 'poisson')
print(rand2.draw())
rand2.summarize()

Parameters of the draw: 

                samples size: 5 

                distribution: poisson 

                interval: 5 

            
[1 5 7 4 8]


'min: 1, max: 8, mean: 5.0, std: 2.449489742783178'

In [11]:
rand3 = GetRandomNums(n_samples = 5, distribution = 'binomial')
print(rand3.draw())
rand3.summarize()

Parameters of the draw: 

                samples size: 5 

                distribution: binomial 

                trials: 10 

                prob: 0.5
            
[3 6 2 7 2]


'min: 2, max: 7, mean: 4.0, std: 2.0976176963403033'

In [12]:
rand4 = GetRandomNums(n_samples = 5, distribution = 'multinomial')
print(rand4.draw())
rand4.summarize()

Parameters of the draw: 

                samples size: 5 

                distribution: multinomial 

            
Distribution not supported!


'Please draw a random sample first!'

In [13]:
rand5 = GetRandomNums(n_samples = 5, distribution = 'normal', mu = 4, sigma = 1)
print(rand5.draw())
rand5.summarize()

Parameters of the draw: 

                samples size: 5 

                distribution: normal 

                mu: 4 

                sigma: 1
            
[3.10469812 5.08752916 4.31424743 5.7948281  6.07260011]


'min: 3.1046981181658846, max: 6.072600107174173, mean: 4.874780581834363, std: 1.074607868448617'